QUESTION_BLUEPRINTS = {
    "Computer vision foundations": [
        {
            "prompt": "A student says computer vision is just recording pixels from a camera. According to the course definition, how should that statement be corrected?",
            "correct": "Computer vision is about interpreting images and video for tasks such as recognition, measurement, and scene understanding.",
            "distractors": [
                "Computer vision is mainly about storing images without interpreting what they show.",
                "Computer vision means recovering exact 3D structure from a single pixel in every scene.",
                "Computer vision is the same thing as manually choosing camera parameters for every image.",
            ],
            "explanation": "The introductory lecture defines computer vision as making computers gain useful understanding from images and videos, not merely storing raw pixels.",
            "review_terms": ["goal of computer vision", "high-level understanding", "images and videos"],
        },
        {
            "prompt": "Why is computer vision considered difficult in the introductory lecture?",
            "correct": "Because real images contain variation, clutter, occlusion, and other factors that make the same object look very different.",
            "distractors": [
                "Because digital images cannot be represented as numeric arrays.",
                "Because every vision task uses exactly the same algorithm and data representation.",
                "Because objects always appear in front of a clean and uniform background.",
            ],
            "explanation": "The lecture highlights intra-class variation, clutter, and occlusion as central sources of difficulty.",
        },
        {
            "prompt": "Which of the following is a typical computer vision task rather than a low-level storage operation?",
            "correct": "Recognizing an object category from an input image.",
            "distractors": [
                "Saving the same image to disk under a different file name.",
                "Replacing a folder path in the operating system.",
                "Counting how many bytes a file occupies without using the image content.",
            ],
            "explanation": "Computer vision is about interpreting image content, such as recognition and scene understanding.",
        },
        {
            "prompt": "What makes a vision system different from simply recording pixels?",
            "correct": "A vision system tries to infer structure or meaning from the visual input, not just keep the raw image values.",
            "distractors": [
                "A vision system can only operate on handwritten images.",
                "A vision system never uses any numerical representation.",
                "A vision system is defined only by the camera focal length.",
            ],
            "explanation": "The course introduction distinguishes understanding visual content from merely storing raw image measurements.",
        },
        {
            "prompt": "Which statement correctly describes the scope of computer vision?",
            "correct": "Computer vision is a broad field with many applications that all depend on interpreting visual information.",
            "distractors": [
                "Computer vision is useful only when the camera has already been perfectly calibrated.",
                "All computer vision applications reduce to one identical low-level filtering problem.",
                "Computer vision is limited to one narrow application area rather than a broad field.",
            ],
            "explanation": "The application collage is used to show breadth: many very different real tasks still rely on extracting meaning from images.",
            "review_terms": ["applications", "robotics", "medical imaging", "recognition"],
        },
    ],
    "Image filtering and convolution": [
        {
            "prompt": "A 3x3 linear filter is applied at one interior pixel. How many input-weight multiplications contribute to that output value?",
            "correct": "9 multiplications.",
            "distractors": [
                "3 multiplications.",
                "6 multiplications.",
                "18 multiplications.",
            ],
            "explanation": "A 3x3 kernel contains 9 weights, so one output value uses 9 multiply terms before summation.",
            "review_terms": ["3x3 filter", "kernel", "linear filtering", "weighted sum"],
        },
        {
            "prompt": "A filter h(x,y) = a(x)b(y) is separable. What practical advantage does this give when filtering an image?",
            "correct": "The 2D convolution can be carried out as two 1D convolutions with fewer operations.",
            "distractors": [
                "The filter must be applied four times instead of once.",
                "The filter can only be used on binary images.",
                "The image no longer needs any interpolation or resampling.",
            ],
            "explanation": "A separable filter reduces the cost by replacing one 2D filtering pass with two cheaper 1D passes.",
            "review_terms": ["separable filter", "two 1D convolutions", "linear filtering"],
        },
        {
            "prompt": "For a non-symmetric kernel, which statement correctly distinguishes convolution from cross-correlation?",
            "correct": "Convolution flips the kernel, while cross-correlation uses the kernel in its original order.",
            "distractors": [
                "Cross-correlation flips the kernel, while convolution keeps it unchanged.",
                "Both operations always produce identical results for every kernel.",
                "Convolution can only be used for color images, while cross-correlation can only be used for grayscale images.",
            ],
            "explanation": "The lecture material explicitly distinguishes convolution from cross-correlation by the kernel flip.",
            "review_terms": ["convolution", "cross-correlation", "kernel flipped"],
        },
        {
            "prompt": "In the figure, the right lower result keeps the thin grass strands slightly clearer than the left lower result. What property of Gaussian smoothing explains that difference?",
            "correct": "Gaussian smoothing gives more weight to nearby pixels, so it reduces noise without flattening local structure as uniformly as a mean filter.",
            "distractors": [
                "Gaussian smoothing flips the kernel, which automatically sharpens every edge in the image.",
                "Gaussian smoothing ignores neighboring pixels and keeps only the center pixel value.",
                "Gaussian smoothing changes the camera focal length so the strands appear sharper.",
            ],
            "explanation": "The comparison is meant to show that Gaussian weighting still smooths noise, but its center-weighted averaging usually preserves fine local structure better than a uniform mean filter.",
            "use_image": True,
            "image_source": "Week1\\Lecture1-2 (10).pptx",
            "image_slide": 30,
            "review_terms": ["mean filter", "Gaussian filter", "grass", "smoothing comparison", "fine structure"],
        },
        {
            "prompt": "In the kernel-over-image diagram, which pixels determine the output value at the marked location?",
            "correct": "Only the pixels covered by the current kernel window contribute, through a weighted sum.",
            "distractors": [
                "Every pixel in the whole image contributes equally to the marked output value.",
                "Only the single center pixel contributes, because filtering does not use neighbors.",
                "The output is determined by camera geometry rather than nearby pixel values.",
            ],
            "explanation": "A local filter uses the pixels under the kernel window only. The output is the weighted combination of that local neighborhood.",
            "use_image": True,
            "review_terms": ["local neighborhood", "kernel", "weighted sum", "linear filtering"],
        },
    ],
    "Edge detection": [
        {
            "prompt": "A vision pipeline extracts strong boundaries before later recognition or matching. What is the edge detector trying to locate?",
            "correct": "Strong intensity discontinuities that often correspond to object boundaries or structure changes.",
            "distractors": [
                "The focal length of the camera from one pixel value.",
                "A set of visual words for large-scale retrieval.",
                "A stereo baseline directly from local brightness alone.",
            ],
            "explanation": "Edge detectors respond where image intensity changes rapidly. Those locations often align with meaningful boundaries and structure.",
            "review_terms": ["edge detection", "discontinuities", "object boundaries"],
        },
        {
            "prompt": "Why is smoothing often applied before computing image derivatives for edge detection?",
            "correct": "Because derivatives amplify noise, so smoothing makes the edge response more stable.",
            "distractors": [
                "Because smoothing converts edges directly into segmentation masks.",
                "Because derivatives can only be computed on binary images.",
                "Because smoothing guarantees the image has no corners.",
            ],
            "explanation": "Noise creates unstable derivative responses, so smoothing is commonly used before edge detection.",
        },
        {
            "prompt": "Where should the strongest edge response appear?",
            "correct": "At locations where the image intensity changes abruptly over a short distance.",
            "distractors": [
                "At perfectly uniform flat regions with constant intensity.",
                "At every pixel with the same response regardless of structure.",
                "Only at the optical center of the camera.",
            ],
            "explanation": "Edges correspond to rapid local intensity variation rather than flat regions.",
        },
        {
            "prompt": "Why are edge maps useful in later vision tasks?",
            "correct": "They preserve important boundary structure while discarding much of the less informative interior appearance.",
            "distractors": [
                "They recover absolute scene depth without any second view.",
                "They replace the need for feature descriptors in all matching tasks.",
                "They always provide the final semantic label of every object.",
            ],
            "explanation": "Edge maps provide a compact representation of salient structural changes in the image.",
        },
        {
            "prompt": "In the displayed output, the face outline and earrings remain visible while broad smooth regions such as the cheek are mostly blank. What does that reveal about the operator?",
            "correct": "It responds strongly to local intensity changes while giving weak response in nearly uniform regions.",
            "distractors": [
                "It is estimating optical flow between two time frames.",
                "It is building a visual-word histogram for retrieval.",
                "It is projecting a 3D scene by the pinhole camera model.",
            ],
            "explanation": "The displayed contour image keeps boundaries and other rapid intensity transitions, while smooth interior regions contribute little response.",
            "use_image": True,
            "image_source": "Week2\\Edge.pptx",
            "image_slide": 2,
            "review_terms": ["edge response", "face outline", "earrings", "flat regions", "discontinuities"],
        },
    ],
    "Image resampling": [
        {
            "prompt": "If an image is subsampled by a factor of 2 without low-pass filtering, what artifact can occur?",
            "correct": "Aliasing artifacts can appear because high-frequency content is sampled too coarsely.",
            "distractors": [
                "The image automatically gains more geometric detail.",
                "The camera focal length becomes smaller.",
                "The image is forced into a corner detector response map.",
            ],
            "explanation": "Downsampling without proper filtering can fold high frequencies into misleading lower-frequency patterns.",
            "use_image": True,
            "review_terms": ["downsampling", "low-pass filtering", "aliasing"],
        },
        {
            "prompt": "When enlarging an image, what is interpolation actually used to compute?",
            "correct": "To estimate pixel values at new sample locations that were not originally present.",
            "distractors": [
                "To recover the exact 3D pose of the camera.",
                "To convert edges into texture descriptors.",
                "To cluster SIFT features into visual words.",
            ],
            "explanation": "Interpolation fills in values when the image grid changes, especially during resizing or warping.",
            "review_terms": ["interpolation", "upsampling", "new sample locations"],
        },
        {
            "prompt": "After upsampling onto a denser grid, what extra information must the algorithm provide?",
            "correct": "New pixel values on a denser grid using an interpolation rule.",
            "distractors": [
                "A disparity map from two rectified images.",
                "A semantic segmentation label for each region.",
                "A fundamental matrix between the original and enlarged images.",
            ],
            "explanation": "Upsampling creates new sample positions that require estimated intensities.",
            "review_terms": ["upsampling", "denser grid", "interpolation"],
        },
        {
            "prompt": "In this course, what does image resampling change?",
            "correct": "It changes how an image is sampled in space while trying to preserve useful visual information.",
            "distractors": [
                "It learns a decision boundary directly from labeled training data.",
                "It computes corner strength from second-moment statistics.",
                "It enforces the coplanarity relation between two camera rays.",
            ],
            "explanation": "Resampling is about changing spatial sampling or resolution rather than recognition or stereo geometry.",
            "review_terms": ["image resampling", "sampling", "resolution"],
        },
        {
            "prompt": "A resized image contains jagged or moire-like patterns after shrinking. Which processing step was likely omitted?",
            "correct": "Downsampling or resampling without adequate low-pass filtering, which causes aliasing.",
            "distractors": [
                "Restricting stereo matching to an epipolar line.",
                "Using CNN pooling to reduce feature-map resolution.",
                "Recovering camera motion from feature tracks.",
            ],
            "explanation": "Resampling figures with jagged or false patterns usually illustrate aliasing, which occurs when sampling is too coarse or insufficiently filtered.",
            "review_terms": ["image resampling", "sampling", "aliasing", "low-pass filtering"],
        },
    ],
    "Texture analysis": [
        {
            "prompt": "What type of visual signal is texture analysis designed to capture?",
            "correct": "Repeated local appearance patterns such as grass, fabric, or brick-like structure.",
            "distractors": [
                "Exact camera intrinsic parameters.",
                "The optical center of the imaging system.",
                "Only the strongest single edge in the whole image.",
            ],
            "explanation": "Texture analysis focuses on repeated local structure rather than isolated geometric primitives.",
        },
        {
            "prompt": "Why can texture be useful for recognition?",
            "correct": "Because different surfaces often produce characteristic repeated local patterns that are discriminative.",
            "distractors": [
                "Because texture removes the need for any segmentation or matching.",
                "Because texture directly returns a 3D point cloud.",
                "Because texture always stays unchanged under every possible transformation.",
            ],
            "explanation": "Texture cues help distinguish surfaces and categories when local appearance patterns differ.",
        },
        {
            "prompt": "Suppose object shape is unreliable, but surface appearance differs between grass, leaves, and brick. Which cue should a recognition system emphasize?",
            "correct": "Repeated local surface patterns such as texture statistics over a region.",
            "distractors": [
                "Estimating the baseline between two calibrated cameras from one point.",
                "Choosing a focal length to widen the field of view.",
                "Projecting a 3D point through a pinhole model.",
            ],
            "explanation": "Texture analysis is about repeated appearance patterns, not camera geometry.",
        },
        {
            "prompt": "Why is texture analysis different from corner detection?",
            "correct": "Texture analysis describes repeated appearance over regions, while corner detection looks for localized point-like structure.",
            "distractors": [
                "Texture analysis uses only 3D points, while corner detection uses only 2D lines.",
                "Texture analysis estimates depth, while corner detection estimates focal length.",
                "Texture analysis requires two cameras, while corner detection requires four cameras.",
            ],
            "explanation": "Texture and corners capture different kinds of information: regional pattern versus localized feature points.",
        },
        {
            "prompt": "The displayed patch is made of many small repeated intensity variations rather than one clean object boundary. Which kind of visual cue should be used to describe it?",
            "correct": "Texture statistics over a region, because the information lies in repeated local patterns rather than one isolated edge or corner.",
            "distractors": [
                "Apparent motion between adjacent video frames.",
                "Epipolar constraints between two cameras.",
                "A global image warp estimated from feature matches.",
            ],
            "explanation": "This kind of patch is recognized by repeated local appearance over an area. A single contour or corner is not the main cue here.",
            "use_image": True,
            "image_source": "Week3\\Lecture3-1 (1).pptx",
            "image_slide": 1,
            "review_terms": ["texture", "repeated local patterns", "surface patch", "leaves"],
        },
    ],
    "Convolutional neural networks": [
        {
            "prompt": "Why are convolutional layers well suited for images?",
            "correct": "They reuse local filters across the image, allowing shared feature detectors at many locations.",
            "distractors": [
                "They require a different weight matrix for every pixel location.",
                "They replace the need for any labeled data.",
                "They compute the essential matrix from a stereo pair.",
            ],
            "explanation": "Convolution exploits local connectivity and weight sharing, which matches the structure of images.",
        },
        {
            "prompt": "What is the role of pooling in a CNN?",
            "correct": "To reduce spatial resolution while preserving strong local evidence and improving robustness.",
            "distractors": [
                "To calibrate the camera's focal length.",
                "To generate a semantic segmentation mask directly from a single pixel.",
                "To convert every descriptor into a geometric transformation matrix.",
            ],
            "explanation": "Pooling compresses feature maps and can make the network less sensitive to small shifts.",
        },
        {
            "prompt": "How do deeper CNN layers usually differ from earlier layers?",
            "correct": "They tend to represent more abstract and task-specific visual patterns.",
            "distractors": [
                "They always contain fewer parameters than the input image.",
                "They stop using any local spatial information at all.",
                "They can only respond to raw grayscale intensity values.",
            ],
            "explanation": "Early layers often capture simple patterns while deeper layers combine them into more semantic features.",
        },
        {
            "prompt": "A CNN is trained to assign one label to each whole image. What is it learning to do?",
            "correct": "The network learns feature hierarchies that help separate image categories with a decision boundary.",
            "distractors": [
                "The network guarantees exact geometric alignment between any two views.",
                "The network enforces brightness constancy for optical flow.",
                "The network computes vanishing points by analytic projection only.",
            ],
            "explanation": "CNNs for classification learn increasingly useful representations for separating classes.",
            "review_terms": ["classification", "decision boundary", "feature hierarchies", "CNN"],
        },
        {
            "prompt": "Why do the course materials contrast early edge-like filters with deeper part-like responses in a CNN?",
            "correct": "CNNs build a hierarchy of features, from simple local patterns to more task-specific representations.",
            "distractors": [
                "Stereo matching becomes one-dimensional after rectification.",
                "A bag-of-words system quantizes descriptors into histogram bins.",
                "Perspective projection maps 3D points to 2D image coordinates.",
            ],
            "explanation": "Feature-map stacks are typically used to show that deeper CNN layers combine simpler responses into more abstract visual patterns.",
            "review_terms": ["feature maps", "hierarchical features", "convolutional neural networks"],
        },
    ],
    "Image segmentation": [
        {
            "prompt": "In the displayed image, each animal is localized by a rectangular box, but the object pixels are not separated from the background. Relative to segmentation, what information is still missing?",
            "correct": "Pixel-level masks or region labels that separate each object from the background.",
            "distractors": [
                "The focal length of the camera in pixel units.",
                "The epipolar line for each object center.",
                "The optical-flow vector at every pixel.",
            ],
            "explanation": "The boxes show object detection. Segmentation would go further by assigning the pixels of each dog, cat, and background region to separate masks or labels.",
            "use_image": True,
            "image_source": "Week4\\lecture4.pptx",
            "image_slide": 13,
            "review_terms": ["bounding boxes", "object detection", "pixel-level masks", "segmentation", "dogs cat"],
        },
        {
            "prompt": "A segmentation system is run on a street image. Which output is the most reasonable?",
            "correct": "A region or mask assignment for pixels belonging to different objects or classes.",
            "distractors": [
                "A single focal-length value for the whole image.",
                "A histogram of visual words only.",
                "A list of camera rotations without any pixel labels.",
            ],
            "explanation": "Segmentation outputs pixel- or region-level assignments, not just image-level labels.",
            "review_terms": ["segmentation output", "mask assignment", "regions"],
        },
        {
            "prompt": "Why is segmentation harder than simple edge detection?",
            "correct": "Because segmentation must group pixels into coherent regions or objects, not just mark local discontinuities.",
            "distractors": [
                "Because segmentation works only on binary images.",
                "Because segmentation cannot use any appearance information.",
                "Because segmentation requires every scene to contain stereo pairs.",
            ],
            "explanation": "Segmentation goes beyond local boundaries and reasons about region consistency and object extent.",
        },
        {
            "prompt": "What makes semantic segmentation different from assigning one class label to the whole image?",
            "correct": "Pixels are assigned to categories such as road, zebra, sky, or person.",
            "distractors": [
                "Only a single corner point is marked in each object.",
                "Each image is reduced to a 3D point cloud directly.",
                "Every descriptor is converted into a camera matrix.",
            ],
            "explanation": "Semantic segmentation labels pixels or regions with category information.",
            "review_terms": ["semantic segmentation", "pixel categories", "road", "sky", "person"],
        },
        {
            "prompt": "If two touching objects receive different region labels in the final output, what has the system done correctly?",
            "correct": "The image has been partitioned into distinct object or semantic regions rather than treated as one undivided area.",
            "distractors": [
                "Estimating stereo disparity between corresponding pixels.",
                "Describing repeated texture for image retrieval.",
                "Normalizing a local descriptor for scale and rotation.",
            ],
            "explanation": "When touching areas are given separate masks or colors, the figure is demonstrating successful segmentation into coherent regions.",
            "review_terms": ["segmentation masks", "object regions", "semantic regions"],
        },
    ],
    "Harris corners and local features": [
        {
            "prompt": "In Harris corner detection, what does it usually mean if one eigenvalue is large and the other is small?",
            "correct": "The local patch is likely an edge rather than a corner.",
            "distractors": [
                "The local patch is a strong corner.",
                "The local patch is completely flat.",
                "The camera focal length is too small.",
            ],
            "explanation": "An edge changes strongly in one direction only, which gives one large and one small eigenvalue.",
        },
        {
            "prompt": "What does it usually mean if both eigenvalues of the Harris matrix are large?",
            "correct": "The local patch is a corner because intensity changes strongly in two directions.",
            "distractors": [
                "The local patch is flat.",
                "The local patch is a pure edge.",
                "The image has already been rectified for stereo.",
            ],
            "explanation": "Corners are the locations where the image patch varies strongly under small shifts in both x and y directions.",
        },
        {
            "prompt": "What does it usually mean if both eigenvalues of the Harris matrix are small?",
            "correct": "The local patch is a flat region with little intensity change.",
            "distractors": [
                "The local patch is a strong corner.",
                "The local patch is a strong edge.",
                "The descriptor has become rotation invariant.",
            ],
            "explanation": "Flat regions do not change much under small shifts, so both directional variations remain small.",
        },
        {
            "prompt": "Which transformation is standard Harris corner detection not invariant to?",
            "correct": "Scaling.",
            "distractors": [
                "Image translation.",
                "Image rotation.",
                "Intensity shift.",
            ],
            "explanation": "The revision slides note that Harris is shift- and rotation-friendly in common settings, but not scale invariant.",
        },
        {
            "prompt": "In the displayed expression E(u, v) = sum[I(x+u, y+v) - I(x, y)]^2, what quantity is E(u, v) measuring?",
            "correct": "How much the image patch changes when the window is shifted by (u, v).",
            "distractors": [
                "The camera focal length used to project the patch into the image.",
                "The semantic class probability of the patch after CNN inference.",
                "The stereo disparity between the left and right cameras.",
            ],
            "explanation": "The SSD expression is the Harris starting point: it measures how different the window looks after a small spatial shift. Corners are the locations where this change becomes large in more than one direction.",
            "use_image": True,
            "image_source": "Week5\\lecture5-1 (5).pptx",
            "image_slide": 25,
            "review_terms": ["SSD error", "E(u, v)", "shifted window", "Harris corner"],
        },
    ],
    "SIFT and scale-invariant features": [
        {
            "prompt": "What role does the Difference-of-Gaussian stage play in SIFT?",
            "correct": "It detects candidate keypoints as extrema across scale space.",
            "distractors": [
                "It computes the final bag-of-words histogram directly.",
                "It rectifies a stereo pair into scanlines.",
                "It replaces the descriptor with a semantic class label.",
            ],
            "explanation": "SIFT first searches for stable extrema across scale space before building descriptors.",
        },
        {
            "prompt": "A full SIFT descriptor uses a 4x4 grid of cells with 8 orientation bins per cell. What is the descriptor dimension?",
            "correct": "128.",
            "distractors": [
                "32.",
                "64.",
                "256.",
            ],
            "explanation": "The lecture slides state 16 cells times 8 orientation bins, which gives 128 dimensions.",
        },
        {
            "prompt": "Why can SIFT remain fairly robust under illumination change?",
            "correct": "Because the descriptor is built from local gradients rather than raw pixel values alone.",
            "distractors": [
                "Because SIFT assumes every image is captured with the same exposure.",
                "Because SIFT always normalizes the camera focal length.",
                "Because SIFT ignores all local structure inside the patch.",
            ],
            "explanation": "The tutorial answer notes that SIFT depends on gradient information, which is more stable than raw brightness values.",
        },
        {
            "prompt": "How does SIFT achieve rotation invariance?",
            "correct": "It aligns the descriptor to a dominant local orientation before describing the patch.",
            "distractors": [
                "It removes all orientation information from the image gradients.",
                "It estimates rotation by comparing stereo disparity values.",
                "It requires the input images to be physically rotated back before matching.",
            ],
            "explanation": "Orientation assignment normalizes the patch before descriptor formation, which makes matching more stable under rotation.",
        },
        {
            "prompt": "In SIFT scale-space detection, what must be true before a candidate point is kept as a keypoint?",
            "correct": "It must be a local extremum compared with neighboring locations and neighboring scales.",
            "distractors": [
                "It must define a stereo baseline between two cameras.",
                "It must satisfy the optical-flow constraint equation.",
                "It must be projected from a 3D point by the pinhole model.",
            ],
            "explanation": "SIFT keeps candidates that are extrema in scale space before orientation assignment and descriptor construction are performed.",
            "review_terms": ["scale space", "Difference-of-Gaussian", "local extrema", "SIFT keypoint"],
        },
    ],
    "Bag-of-words image retrieval": [
        {
            "prompt": "After extracting many local descriptors from an image, which representation allows the system to compare whole images efficiently for retrieval?",
            "correct": "A histogram of visual words built by quantizing the local descriptors.",
            "distractors": [
                "A single strongest corner point from the image.",
                "A full semantic segmentation mask of the image.",
                "Only the camera intrinsic matrix of the image.",
            ],
            "explanation": "Bag-of-words retrieval replaces many local descriptors with counts over a visual vocabulary, making whole-image comparison efficient.",
            "review_terms": ["bag of words", "visual words", "histogram", "local descriptors"],
        },
        {
            "prompt": "What is a visual vocabulary in a bag-of-words retrieval pipeline?",
            "correct": "A set of prototype descriptor clusters used to quantize local features into visual words.",
            "distractors": [
                "A list of all object names in the dataset.",
                "A matrix that enforces the epipolar constraint.",
                "A collection of camera baselines from stereo pairs.",
            ],
            "explanation": "Visual words come from clustering local descriptors into representative prototypes.",
        },
        {
            "prompt": "Why can bag-of-words support large-scale retrieval?",
            "correct": "Because histograms of visual words give a compact representation that can be compared efficiently.",
            "distractors": [
                "Because it stores every image as a full 3D point cloud.",
                "Because it removes the need for any feature extraction.",
                "Because it estimates optical flow between all image pairs.",
            ],
            "explanation": "Histogram representations are compact and efficient for indexing and matching.",
        },
        {
            "prompt": "What information does a plain bag-of-words model usually lose?",
            "correct": "The exact spatial arrangement of the local features in the image.",
            "distractors": [
                "Whether the image contains any pixel values at all.",
                "Whether the camera uses perspective projection.",
                "Whether edges correspond to intensity changes.",
            ],
            "explanation": "A plain histogram keeps counts of visual words but not their exact geometry.",
        },
        {
            "prompt": "If several local descriptors are assigned to the same visual-word bin, what changes in the bag-of-words representation?",
            "correct": "The histogram count of that visual word increases.",
            "distractors": [
                "The estimated depth of the image point increases.",
                "The optical-flow magnitude between frames increases.",
                "The focal length of the camera increases.",
            ],
            "explanation": "Bag-of-words representations count how many local descriptors fall into each visual-word bin, so repeated assignments raise that bin count.",
            "review_terms": ["visual vocabulary", "histogram counts", "quantization", "local descriptors"],
        },
    ],
    "Geometric transformations": [
        {
            "prompt": "Which homogeneous coordinate represents the same 2D point as (3, 2, 1)?",
            "correct": "(6, 4, 2).",
            "distractors": [
                "(6, 2, 1).",
                "(3, 2, 2).",
                "(4, 6, 2).",
            ],
            "explanation": "Homogeneous coordinates that differ by a nonzero scale factor represent the same Cartesian point.",
        },
        {
            "prompt": "Which transformation class combines linear transformations with translation?",
            "correct": "An affine transformation.",
            "distractors": [
                "A Gaussian transformation.",
                "A bag-of-words transformation.",
                "A disparity transformation.",
            ],
            "explanation": "The course notes define affine transformations as linear transforms together with translations.",
        },
        {
            "prompt": "Which motion cannot be represented by a 2x2 linear matrix alone and is usually added via homogeneous coordinates?",
            "correct": "Translation.",
            "distractors": [
                "Rotation about the origin.",
                "Uniform scaling.",
                "Shear.",
            ],
            "explanation": "A pure 2x2 linear transform handles operations about the origin, while translation is added naturally in homogeneous coordinates.",
        },
        {
            "prompt": "In the simple image-alignment case where the transform is pure translation, what is the least-squares estimate from feature matches?",
            "correct": "The mean displacement vector across the matches.",
            "distractors": [
                "The largest single displacement vector only.",
                "The disparity with the smallest magnitude.",
                "The camera principal point.",
            ],
            "explanation": "The lecture slides state that for translation, the least-squares solution is the average displacement of the matched points.",
        },
        {
            "prompt": "A global warp preserves straight structures in the image. What family of mappings is being illustrated?",
            "correct": "A global geometric transform, such as affine or related coordinate warping.",
            "distractors": [
                "A SIFT descriptor is being turned into a bag-of-words histogram.",
                "Stereo disparity is being converted into scene depth.",
                "A CNN is assigning semantic labels to image regions.",
            ],
            "explanation": "Transformation figures typically show how one global mapping changes image coordinates while preserving geometric structure such as straight lines.",
            "review_terms": ["geometric transformations", "affine", "warping", "image coordinates"],
        },
    ],
    "Image alignment": [
        {
            "prompt": "The displayed pair is covered with correspondence lines linking matched points. Before one image can be warped onto the other, what must be estimated from these matches?",
            "correct": "A geometric transform, such as a homography, that best aligns the matched points.",
            "distractors": [
                "Estimate a segmentation mask for each image independently.",
                "Replace all feature matches with a CNN classifier.",
                "Recover depth from a single image without any geometry.",
            ],
            "explanation": "Matched correspondences are not the final output. They are the evidence used to estimate the transform that will align one image with the other.",
            "use_image": True,
            "image_source": "Week8\\Lecture7-2 (2).pptx",
            "image_slide": 2,
            "review_terms": ["feature matches", "correspondence lines", "homography", "alignment"],
        },
        {
            "prompt": "In the lecture alignment pipeline, what is typically estimated after computing and matching image features?",
            "correct": "A homography or other geometric transform between the two images.",
            "distractors": [
                "A bag-of-words vocabulary.",
                "A dense semantic segmentation map.",
                "A stereo baseline from a calibrated rig.",
            ],
            "explanation": "The course alignment algorithm computes features, matches them, and then estimates a homography from those matches.",
        },
        {
            "prompt": "Why is RANSAC used before the final least-squares fit in image alignment?",
            "correct": "To remove outlier matches and keep the transform supported by the largest inlier set.",
            "distractors": [
                "To increase the image brightness before matching.",
                "To convert the images into grayscale histograms.",
                "To replace the transform with semantic labels.",
            ],
            "explanation": "RANSAC is used to reject mismatches so the final transform is estimated from geometrically consistent correspondences.",
        },
        {
            "prompt": "In inverse warping, where does each output pixel g(x', y') sample its value from?",
            "correct": "From the source image location T^-1(x', y') in the input image.",
            "distractors": [
                "From the output image location T(x', y') itself.",
                "From the camera center in 3D space.",
                "From the largest SIFT bin only.",
            ],
            "explanation": "Inverse warping fills each output pixel by mapping backward through the inverse transform into the source image.",
        },
        {
            "prompt": "After warping one image onto another, corresponding structures overlap closely. What does that indicate?",
            "correct": "Corresponding structures from the two images overlap consistently after warping.",
            "distractors": [
                "Every image edge disappears after filtering.",
                "The camera focal length changes automatically.",
                "Optical flow is computed for every video frame.",
            ],
            "explanation": "Image alignment is successful when the warped source and target image content line up well.",
        },
    ],
    "Camera model and projection": [
        {
            "prompt": "A pinhole camera has focal length 5 mm and pixel size 0.02 mm. What is the focal length in pixel units?",
            "correct": "250 pixels.",
            "distractors": [
                "25 pixels.",
                "100 pixels.",
                "500 pixels.",
            ],
            "explanation": "Dividing 5 mm by 0.02 mm per pixel gives 250 pixels for both fx and fy.",
            "review_terms": ["pinhole camera", "focal length", "pixel units"],
        },
        {
            "prompt": "Using focal length 5 mm, pixel size 0.02 mm, and principal point (500, 500), what is the image projection of the 3D point (100, 150, 800) when world and camera coordinates are aligned?",
            "correct": "(531.25, 546.875).",
            "distractors": [
                "(31.25, 46.875).",
                "(525, 537.5).",
                "(546.875, 531.25).",
            ],
            "explanation": "fx = fy = 250, so x = 250*(100/800)+500 = 531.25 and y = 250*(150/800)+500 = 546.875.",
            "review_terms": ["projection", "principal point", "focal length", "pinhole camera"],
        },
        {
            "prompt": "Two photos are taken with the same sensor, but the second uses a longer focal length. What change should appear in the second image?",
            "correct": "The field of view becomes narrower and objects appear larger in the image.",
            "distractors": [
                "The field of view becomes wider and objects appear smaller.",
                "The principal point disappears from the camera model.",
                "All stereo disparity values become zero automatically.",
            ],
            "explanation": "Increasing focal length enlarges the projected image scale and narrows the field of view when the sensor size is unchanged.",
            "review_terms": ["focal length", "field of view", "pinhole camera"],
        },
        {
            "prompt": "Why do vanishing points appear in perspective images?",
            "correct": "Parallel 3D lines that are not parallel to the image plane can project to image lines that meet at a point.",
            "distractors": [
                "Because every 3D line stays parallel after perspective projection.",
                "Because vanishing points are caused only by Gaussian filtering.",
                "Because the principal point always lies on every 3D line.",
            ],
            "explanation": "Vanishing points are a direct consequence of perspective projection of sets of parallel scene lines.",
            "review_terms": ["vanishing point", "perspective projection", "parallel lines"],
        },
        {
            "prompt": "In the ray diagram, the red rays cross at the pinhole before reaching the image plane. What geometric effect does that crossing explain?",
            "correct": "Because light rays from the scene cross at the small aperture before reaching the image plane.",
            "distractors": [
                "Because the camera automatically rotates every scene point by 180 degrees.",
                "Because image inversion is introduced later by stereo rectification.",
                "Because the principal point forces all projected rays to flip vertically.",
            ],
            "explanation": "The diagram shows the rays crossing at the aperture, which is exactly why the physical image plane receives an inverted projection of the scene.",
            "use_image": True,
            "image_source": "Week8\\cameras.pptx",
            "image_slide": 7,
            "review_terms": ["pinhole camera", "image plane", "virtual image", "rays", "image inversion"],
        },
    ],
    "Stereo vision and depth": [
        {
            "prompt": "In the stereo relation z = fB / d, what happens to depth if disparity doubles while f and B stay fixed?",
            "correct": "The depth is halved.",
            "distractors": [
                "The depth doubles.",
                "The depth stays the same.",
                "The depth becomes zero regardless of the scene point.",
            ],
            "explanation": "Depth is inversely proportional to disparity, so doubling disparity cuts depth by a factor of two.",
        },
        {
            "prompt": "Why is stereo rectification applied before dense matching in a calibrated stereo pair?",
            "correct": "It turns epipolar lines into horizontal scanlines, so the search becomes one-dimensional.",
            "distractors": [
                "It removes the need for camera calibration entirely.",
                "It converts disparity directly into a segmentation mask.",
                "It makes every image patch rotation invariant.",
            ],
            "explanation": "The stereo lecture states that rectification makes pixel motion horizontal and simplifies correspondence search.",
        },
        {
            "prompt": "Two points in the same stereo pair have disparities 8 and 16 pixels. Which point is closer to the cameras?",
            "correct": "The point with disparity 16 pixels.",
            "distractors": [
                "The point with disparity 8 pixels.",
                "They are at the same depth.",
                "The answer depends only on the principal point, not disparity.",
            ],
            "explanation": "Larger disparity means the scene point is closer when the stereo rig is fixed.",
        },
        {
            "prompt": "In the basic stereo matching algorithm, which quantity is computed immediately before depth?",
            "correct": "Disparity, computed as the horizontal difference x - x'.",
            "distractors": [
                "The Harris corner response.",
                "The dominant SIFT orientation.",
                "The vanishing point of the scene.",
            ],
            "explanation": "The lecture pipeline is: find correspondence, compute disparity, then convert disparity to depth.",
        },
        {
            "prompt": "In a rectified stereo pair, the same object appears with a larger horizontal shift between left and right images. What does that imply about depth?",
            "correct": "It is closer to the cameras, because larger disparity implies smaller depth in the stereo setup.",
            "distractors": [
                "It is farther away, because disparity grows with depth.",
                "Its depth is unchanged, because horizontal shift carries no geometric meaning.",
                "Its segmentation label has changed rather than its depth.",
            ],
            "explanation": "In a fixed stereo rig, nearer points produce larger disparities. The horizontal offset is exactly the cue used to recover depth.",
            "review_terms": ["stereo", "disparity", "depth", "horizontal shift"],
        },
    ],
    "Epipolar geometry": [
        {
            "prompt": "For a point selected in image 1, where can its corresponding point lie in image 2 according to epipolar geometry?",
            "correct": "On the associated epipolar line.",
            "distractors": [
                "At any pixel in the second image with no geometric restriction.",
                "Only at the principal point.",
                "Only at a Harris corner with the largest response.",
            ],
            "explanation": "A point in one view maps to an epipolar line in the other view, which is the core search constraint.",
            "review_terms": ["epipolar line", "correspondence", "epipolar geometry"],
        },
        {
            "prompt": "In the displayed two-view geometry, once point p is fixed in the left image, what does the line l' in the right image represent?",
            "correct": "The epipolar line on which the corresponding point p' must lie.",
            "distractors": [
                "The image row containing the camera principal point only.",
                "The boundary of the object's segmentation mask.",
                "The orientation bin selected by a SIFT descriptor.",
            ],
            "explanation": "The geometric diagram shows the key epipolar constraint: a point in one image does not map to the whole second image, but to one specific epipolar line.",
            "use_image": True,
            "image_source": "Week10\\lecture10-1 (4).pptx",
            "image_slide": 8,
            "review_terms": ["epipolar line", "p'", "l'", "epipolar plane", "two-view geometry"],
        },
        {
            "prompt": "In an uncalibrated two-view setting, which matrix relates corresponding image points?",
            "correct": "The fundamental matrix.",
            "distractors": [
                "The Gaussian smoothing matrix.",
                "The segmentation confusion matrix.",
                "The SIFT orientation matrix.",
            ],
            "explanation": "The fundamental matrix links image points across uncalibrated views.",
            "review_terms": ["fundamental matrix", "uncalibrated views", "image points"],
        },
        {
            "prompt": "The two camera centers and a 3D scene point define which plane?",
            "correct": "The epipolar plane.",
            "distractors": [
                "The image plane only.",
                "The focal plane only.",
                "A segmentation region.",
            ],
            "explanation": "The two camera centers and the 3D point define the epipolar plane, from which the epipolar lines are induced.",
            "review_terms": ["epipolar plane", "camera centers", "3D point"],
        },
        {
            "prompt": "Once a point is fixed in image 1, why is the search in image 2 restricted to a line rather than the whole image?",
            "correct": "Because epipolar geometry constrains the corresponding point to lie on the associated epipolar line.",
            "distractors": [
                "Because SIFT normalization removes the need to search elsewhere.",
                "Because bag-of-words quantization replaces geometric search.",
                "Because CNN pooling reduces the image to one spatial position.",
            ],
            "explanation": "The practical value of epipolar geometry is exactly this reduction of correspondence search from a 2D region to a 1D epipolar line.",
            "review_terms": ["epipolar line", "epipolar plane", "correspondence search", "baseline"],
        },
    ],
    "Structure from motion": [
        {
            "prompt": "How does structure from motion differ from traditional stereo vision in the course materials?",
            "correct": "SfM can work with multiple images and arbitrary camera motion while jointly estimating camera poses and 3D structure.",
            "distractors": [
                "SfM requires exactly two rectified cameras with fixed known baseline.",
                "SfM ignores camera motion and estimates only image smoothing.",
                "SfM is only another name for edge detection.",
            ],
            "explanation": "The tutorial notes contrast SfM with stereo by emphasizing arbitrary motion and joint estimation of structure and camera pose.",
        },
        {
            "prompt": "What kind of input does an SfM pipeline need?",
            "correct": "Multiple overlapping 2D images of the same scene, optionally with known intrinsics.",
            "distractors": [
                "A single segmented image only.",
                "A 1D signal with no image coordinates.",
                "Only a disparity map with no original images.",
            ],
            "explanation": "The tutorial Q&A states that SfM uses multiple 2D images of the same scene and may also use known camera intrinsics.",
        },
        {
            "prompt": "Why is RANSAC applied to feature matches in a typical SfM pipeline?",
            "correct": "To reject outlier correspondences before estimating the two-view geometry.",
            "distractors": [
                "To enlarge the camera baseline automatically.",
                "To convert the matches into CNN feature maps.",
                "To remove the need for camera pose estimation.",
            ],
            "explanation": "The tutorial material describes RANSAC as fitting a model, counting inliers, and rejecting outliers among matches.",
        },
        {
            "prompt": "What does the reconstructed sparse point cloud in SfM represent?",
            "correct": "Estimated 3D scene points recovered from multiple images.",
            "distractors": [
                "A histogram of visual words for retrieval.",
                "A dense semantic segmentation map.",
                "Only the set of camera intrinsics.",
            ],
            "explanation": "Sparse 3D points are a standard SfM output, reconstructed from repeated observations across views.",
        },
        {
            "prompt": "A reconstruction result shows estimated camera poses around a sparse 3D point cloud. What has been recovered?",
            "correct": "Both the scene structure and the camera poses from multiple overlapping images.",
            "distractors": [
                "Dense optical flow between a pair of neighboring frames only.",
                "A local smoothing result from image filtering.",
                "A bag-of-words histogram for image retrieval.",
            ],
            "explanation": "An SfM reconstruction is typically visualized by camera poses together with a sparse 3D point cloud, indicating joint recovery of motion and structure.",
            "review_terms": ["structure from motion", "camera poses", "sparse point cloud", "3D structure"],
        },
    ],
    "Motion and optical flow": [
        {
            "prompt": "When Lucas-Kanade derives the optical-flow constraint equation for a moving point, which assumption is being used?",
            "correct": "The same moving point keeps approximately the same image brightness between nearby frames.",
            "distractors": [
                "Every moving point keeps exactly the same depth in world coordinates.",
                "Every frame has the same global histogram after smoothing.",
                "The camera focal length changes together with the motion field.",
            ],
            "explanation": "Lucas-Kanade starts from the assumption that the brightness of a moving image point does not change much over a short time interval.",
            "review_terms": ["brightness constancy", "Lucas-Kanade", "optical flow constraint"],
        },
        {
            "prompt": "If motion is observed only through a small aperture on a straight edge, which motion component can usually be estimated reliably?",
            "correct": "Only the motion component perpendicular to the edge.",
            "distractors": [
                "Only the motion component parallel to the edge.",
                "The full 2D motion vector with no ambiguity.",
                "Only the scene depth of the point.",
            ],
            "explanation": "This is the aperture problem: a straight edge gives insufficient information to determine full 2D motion.",
            "review_terms": ["aperture problem", "straight edge", "perpendicular motion"],
        },
        {
            "prompt": "Why does Lucas-Kanade usually aggregate information over a small neighborhood instead of using a single pixel only?",
            "correct": "Because one pixel gives too little information to solve for the two motion components reliably.",
            "distractors": [
                "Because a single pixel already gives three independent motion equations.",
                "Because neighborhoods remove the need for brightness constancy.",
                "Because neighborhoods guarantee perfect semantic segmentation.",
            ],
            "explanation": "The optical-flow equation alone is underconstrained, so Lucas-Kanade uses nearby pixels and spatial coherence to estimate motion.",
            "review_terms": ["Lucas-Kanade", "one equation two unknowns", "small neighborhood"],
        },
        {
            "prompt": "What is the purpose of the coarse-to-fine pyramid used in iterative optical flow estimation?",
            "correct": "It allows larger motions to be handled by first solving them at coarse resolution and then refining at finer levels.",
            "distractors": [
                "It removes the need to warp images during refinement.",
                "It converts optical flow into stereo disparity.",
                "It guarantees that brightness constancy is always exact.",
            ],
            "explanation": "The lecture shows Gaussian pyramids and iterative refinement so that large displacements become easier to estimate.",
            "review_terms": ["coarse-to-fine", "Gaussian pyramid", "large motions", "optical flow"],
        },
        {
            "prompt": "In an optical-flow field, what does a longer motion vector at a pixel indicate?",
            "correct": "A larger magnitude of apparent image motion at that pixel.",
            "distractors": [
                "A higher probability that the pixel belongs to a semantic class.",
                "A longer projection ray in the pinhole camera model.",
                "A larger visual-word cluster center in bag-of-words retrieval.",
            ],
            "explanation": "Optical-flow arrows encode motion vectors, so longer arrows represent larger estimated image displacement magnitudes.",
            "review_terms": ["optical flow", "motion vectors", "arrow field", "apparent motion"],
        },
    ],
    "LLM prompting and DeepSeek overview": [
        {
            "prompt": "What is the main purpose of prompt design in an LLM workflow?",
            "correct": "To steer the model toward the desired task, format, and reasoning behavior.",
            "distractors": [
                "To estimate camera motion from multiple views.",
                "To replace local descriptors with epipolar geometry.",
                "To compute disparity from a rectified stereo pair.",
            ],
            "explanation": "Prompting controls how the model interprets and responds to the task.",
        },
        {
            "prompt": "What is the difference between zero-shot and few-shot prompting?",
            "correct": "Few-shot prompting provides example demonstrations, while zero-shot prompting does not.",
            "distractors": [
                "Zero-shot prompting uses images only, while few-shot prompting uses text only.",
                "Few-shot prompting works only for segmentation tasks.",
                "Zero-shot prompting requires a calibrated stereo rig.",
            ],
            "explanation": "Few-shot prompting supplies examples to guide the model's behavior.",
        },
        {
            "prompt": "Why can a more explicit prompt improve an LLM answer?",
            "correct": "Because clearer task instructions reduce ambiguity about the expected output.",
            "distractors": [
                "Because explicit prompts guarantee perfect factual accuracy.",
                "Because explicit prompts eliminate the need for any model weights.",
                "Because explicit prompts convert LLMs into optical-flow solvers.",
            ],
            "explanation": "Specific instructions often help the model format and focus its response more appropriately.",
        },
        {
            "prompt": "What is the main idea behind chain-of-thought prompting in this lecture topic?",
            "correct": "Encourage the model to expose intermediate reasoning steps when solving a task.",
            "distractors": [
                "Force the model to output only single-token answers.",
                "Replace all language understanding with geometric warping.",
                "Compute a bag-of-words histogram before every response.",
            ],
            "explanation": "Chain-of-thought prompting is about eliciting a more explicit reasoning process.",
        },
        {
            "prompt": "A slide comparing prompt styles, model capabilities, or reasoning behavior is most likely illustrating which lecture theme?",
            "correct": "How prompting choices and model design influence LLM outputs and reasoning quality.",
            "distractors": [
                "How disparity changes with stereo depth.",
                "How Harris corners respond to intensity variation.",
                "How a pinhole camera projects 3D points onto the image.",
            ],
            "explanation": "Comparison charts or reasoning examples are typical visuals for an LLM prompting lecture.",
            "use_image": True,
        },
    ],
}
